Change identation from 2 to 4

diff --git a/roles/configure_maintenance/templates/maintenance.j2 b/roles/configure_maintenance/templates/maintenance.j2
--- a/roles/configure_maintenance/templates/maintenance.j2
+++ b/roles/configure_maintenance/templates/maintenance.j2
@@ -1,74 +1,74 @@
 #!/bin/bash
 # vim:ft=bash
 function error() {
-  local MESSAGE="$1"
-  # Check if stderr is in interactive mode
-  if [[ -t 2 ]]; then
-    >&2 printf "%b\n" "\033[01;31mERROR\033[0m: $MESSAGE"
-  else
-    >&2 printf "%s\n" "ERROR: $MESSAGE"
-  fi
-  exit 1
+    local MESSAGE="$1"
+    # Check if stderr is in interactive mode
+    if [[ -t 2 ]]; then
+        >&2 printf "%b\n" "\033[01;31mERROR\033[0m: $MESSAGE"
+    else
+        >&2 printf "%s\n" "ERROR: $MESSAGE"
+    fi
+    exit 1
 }
 
 # Function that displays info messages
 function info() {
-  local MESSAGE="$1"
-  # Check if stdout is in interactive mode
-  if [[ -t 1 ]]; then
-    printf "%b\n" "\033[01;34mINFO\033[0m: $MESSAGE"
-  else
-    printf "%s\n" "INFO: $MESSAGE"
-  fi
+    local MESSAGE="$1"
+    # Check if stdout is in interactive mode
+    if [[ -t 1 ]]; then
+        printf "%b\n" "\033[01;34mINFO\033[0m: $MESSAGE"
+    else
+        printf "%s\n" "INFO: $MESSAGE"
+    fi
 }
 
 # Check if the script is run as root
 function checkRoot() {
-  if ((EUID != 0)); then
-    error "Please run this script as root"
-  fi
+    if ((EUID != 0)); then
+        error "Please run this script as root"
+    fi
 }
 
 # Renew certificates
 function renewCerts() {
-  local CERTBOT_DIR="{{ config_dir }}/certbot"
+    local CERTBOT_DIR="{{ config_dir }}/certbot"
 
-  info "Renewing certificates..."
-  # Run Certbot docker compose and renew certificates
-  docker compose --file "$CERTBOT_DIR/compose-renew.yaml" up --detach
-  info "Certificates renewed successfully"
+    info "Renewing certificates..."
+    # Run Certbot docker compose and renew certificates
+    docker compose --file "$CERTBOT_DIR/compose-renew.yaml" up --detach
+    info "Certificates renewed successfully"
 }
 
 # Update containers
 function updateContainers() {
-  local PROSODY_DIR="{{ config_dir }}/prosody"
-  local COTURN_DIR="{{ config_dir }}/coturn"
+    local PROSODY_DIR="{{ config_dir }}/prosody"
+    local COTURN_DIR="{{ config_dir }}/coturn"
 
-  info "Updating Prosody..."
-  # Rebuild Prosody image
-  docker build --no-cache --file "$PROSODY_DIR/Dockerfile" --tag "prosody:{{ prosody_ver }}" "$PROSODY_DIR"
-  # Update Postgres image
-  docker compose --file "$PROSODY_DIR/compose.yaml" pull postgres
-  # Recreate Prosody container
-  docker compose --file "$PROSODY_DIR/compose.yaml" up --force-recreate --detach
-  info "Prosody successfully updated!"
+    info "Updating Prosody..."
+    # Rebuild Prosody image
+    docker build --no-cache --file "$PROSODY_DIR/Dockerfile" --tag "prosody:{{ prosody_ver }}" "$PROSODY_DIR"
+    # Update Postgres image
+    docker compose --file "$PROSODY_DIR/compose.yaml" pull postgres
+    # Recreate Prosody container
+    docker compose --file "$PROSODY_DIR/compose.yaml" up --force-recreate --detach
+    info "Prosody successfully updated!"
 
-  info "Updating Coturn..."
-  # Update Coturn image
-  docker compose --file "$COTURN_DIR/compose.yaml" pull
-  # Recreate Coturn container
-  docker compose --file "$COTURN_DIR/compose.yaml" up --force-recreate --detach
-  info "Coturn successfully updated!"
+    info "Updating Coturn..."
+    # Update Coturn image
+    docker compose --file "$COTURN_DIR/compose.yaml" pull
+    # Recreate Coturn container
+    docker compose --file "$COTURN_DIR/compose.yaml" up --force-recreate --detach
+    info "Coturn successfully updated!"
 
-  info "Cleaning up..."
-  # Remove unnecessary things
-  docker system prune --all --force
+    info "Cleaning up..."
+    # Remove unnecessary things
+    docker system prune --all --force
 }
 
 function main() {
-  checkRoot
-  renewCerts
-  updateContainers
+    checkRoot
+    renewCerts
+    updateContainers
 }
 
 # Stop script execution immediately
diff --git a/roles/install_prosody/files/prosody/entrypoint b/roles/install_prosody/files/prosody/entrypoint
--- a/roles/install_prosody/files/prosody/entrypoint
+++ b/roles/install_prosody/files/prosody/entrypoint
@@ -5,47 +5,47 @@ set -o "errexit"
 declare DATA_DIR_OWNER="$(stat -c %u "/var/lib/prosody/")"
 declare MODULE_DIR="/var/lib/prosody/custom_plugins/share/lua/5.4"
 declare -a MODULES=(
-  "firewall"
-  "block_registrations"
-  "spam_reporting"
-  "watch_spam_reports"
-  "muc_limits"
+    "firewall"
+    "block_registrations"
+    "spam_reporting"
+    "watch_spam_reports"
+    "muc_limits"
 )
 
 # Set permissions
 if [[ "$(id -u prosody)" != "$DATA_DIR_OWNER" ]]; then
-  # FIXME this fails if owned by root
-  usermod -u "$DATA_DIR_OWNER" prosody
+    # FIXME this fails if owned by root
+    usermod -u "$DATA_DIR_OWNER" prosody
 fi
 if [[ "$(stat -c %u /var/run/prosody/)" != "$DATA_DIR_OWNER" ]]; then
-  chown "$DATA_DIR_OWNER" "/var/run/prosody/"
+    chown "$DATA_DIR_OWNER" "/var/run/prosody/"
 fi
 
 if [[ "$1" != "prosody" ]]; then
-  exec prosodyctl "$@"
-  exit 0
+    exec prosodyctl "$@"
+    exit 0
 fi
 
 # Import certificates to Prosody
 if [[ -d "/etc/letsencrypt/live" ]]; then
-  prosodyctl --root cert import "/etc/letsencrypt/live"
+    prosodyctl --root cert import "/etc/letsencrypt/live"
 else
-  printf "%s\n" "Certificates directory doesn't exist"
-  exit 1
+    printf "%s\n" "Certificates directory doesn't exist"
+    exit 1
 fi
 
 # Register admin user
 if [[ "$USERNAME" && "$VHOST" && "$PASSWORD" ]]; then
-  prosodyctl register "$USERNAME" "$VHOST" "$PASSWORD"
+    prosodyctl register "$USERNAME" "$VHOST" "$PASSWORD"
 fi
 
 # Install modules
 for MODULE in "${MODULES[@]}"; do
-  # If you don't want to update modules each time prosody launches
-  # Uncomment this conditional statement
-  # if [[ ! -e "$MODULE_DIR/mod_$MODULE.lua" ]]; then
+    # If you don't want to update modules each time prosody launches
+    # Uncomment this conditional statement
+    # if [[ ! -e "$MODULE_DIR/mod_$MODULE.lua" ]]; then
     prosodyctl install --server=https://modules.prosody.im/rocks/ mod_"$MODULE"
-  # fi
+    # fi
 done
 
 # Run Prosody
